baseurl = "https://vyrn.ru"
title = "vyrn"
languageCode = "ru-ru"
theme = "hello-friend-ng"
defaultContentLanguage = 'ru'
defaultContentLanguageInSubdir = true

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

# Subtitle for home
homeSubtitle = "A simple and beautiful blog"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = true

# Metadata mostly used in document's head
description = "Personal blog of Eugene Aldoshkin"
keywords = "homepage, blog"
images = [""]

[taxonomies]
category = "blog"
tag = "tags"
series = "series"

[languages]
[languages.ru]
title = "Vyrn"
contentDir = 'content/ru'
disabled = false
languageCode = 'ru-RU'
languageDirection = 'ltr'
languageName = 'Русский'
weight = 1
[languages.ru.params]
subtitle = 'Личный блог Евгений Алдошкина'
[languages.ru.logo]
logoText = "vyrn"
logoHomeLink = "/"
[languages.ru.params.logo]
logoText = "vyrn"
logoHomeLink = "/"
# [languages.ru.menu]
# [[languages.ru.menu.main]]
# identifier = "home"
# name = "Главная"
# url = "/"
# weight = 1


[languages.en]
title = "Vyrn"
contentDir = 'content/en'
disabled = false
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
weight = 2
[languages.en.params]
subtitle = "Personal blog of Eugene Aldoshkin"
[languages.en.logo]
logoText = "vyrn"
logoHomeLink = "/"
[languages.en.params.logo]
logoText = "vyrn"
logoHomeLink = "/"

# And you can even create generic menu
[menu]

[[menu.main]]
identifier = "AI"
name = "AI"
url = "/"
weight = 1

[[menu.main]]
identifier = "K8s"
name = "K8s"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "Golang"
name = "Golang"
url = "/services/"
weight = 3

[[menu.main]]
identifier = "Linux"
name = "Linux"
url = "/posts"

[[menu.main]]
identifier = "About me"
name = "About me"
url = "/posts"
weight = 100
